name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: rustup toolchain add 1.76.0 --profile minimal
    - name: Get Verus FMT
      run: cargo install verusfmt
    - name: Format
      run:  make -f Verifile format_check

