name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.76.0" # or specify a version like "1.64.0"
        override: true
    - name: Set up Verus
      run: ./tools/ci-setup-verus.sh

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          ${{ github.workspace }}/verus/source -> target
          ${{ github.workspace }}/verus/tools/vargo -> target
        cache-directories: ${{ github.workspace }}/verus/source/target-verus

    - name: Verus cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/verus
        key: ${{ runner.os }}-verus-${{ hashFiles('verus/.git/refs/heads/main') }}

    - name: Build Verus
      run: ./tools/ci-build-verus.sh
    - name: Verify
      run:  make -f Verifile
    - name: Get Verus FMT
      run: cargo install verusfmt
    - name: Format
      run:  make -f Verifile format_check

